### ISSUE TITLE
dead link to example notebook

### ISSUE THREAD

**Issue by Ohjeah** [Jarino/pycgp#1]
https://github.com/Jarino/pycgp-notebooks/blob/master/Symbolic%20regression.ipynb does not exist

**Comment by Jarino** [comment]
I forgot to keep pycgp-notebooks repository up to date. I pushed my local changes now. I also updated the readme in pycgp repository. Note, that Symbolic Regression 2D is broken right now (I was trying out FFX library, but didn’t have time to polish the notebook).

JL

Od: Markus Quade
Odoslané: Friday, February 9, 2018 10:59
Komu: Jarino/pycgp
Kópia: Subscribed
Predmet: [Jarino/pycgp] dead link to example notebook (#1)

https://github.com/Jarino/pycgp-notebooks/blob/master/Symbolic%20regression.ipynb does not exist

**Comment by Ohjeah** [comment]
No worries, thanks for pointing me to the repo.

I've implemented [ffx compatible to the sklearn interface](https://github.com/Ohjeah/sparsereg). It id a bit slower, but plays better with gridsearch.
